# Generated by Django 3.0.8 on 2020-08-16 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyle_gannon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='clicks',
        ),
    ]
